# The netlify.toml file affects only the Netlify preview pages that get generated for pull requests.

# This headers entry allows Remix to pull sample code files from our /samples/ directory on docs.chain.link.
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/samples/**/*"

  [headers.values]
    Access-Control-Allow-Origin = "*"
