name: Build and Deploy
on: 
  push: 
    branches: 
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@94389a881adad57284e35860f5d258ab262dcd91
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}