name: Build and Publish Feed Resources

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build-feeds:
    name: Update latest feed data from source repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Install Dependencies
        run: yarn
      - name: Checkout Data Source Repo
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          repository: smartcontractkit/reference-data-directory
          path: data-source
          token: ${{ secrets.GH_API_KEY }}
      # - name: Read Data Source
      #   run: cat data-source/package.json
      - name: Process Data
        run: yarn process
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@94389a881adad57284e35860f5d258ab262dcd91
        with:

          args: -c firebase-addresses.json deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: cl-docs-addresses
